#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[fix.tools.prettier]
command = ["env", "pnpm_config_use_stderr=true", "pnpm", "exec", "prettier", "--stdin-filepath", "$path"]
patterns = ["glob:'**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx,html,css,json,jsonc,yaml,yml,md,mdx}'"]

[aliases]
lint = ["util", "exec", "--", "sh", "-c", """
set -e

files=$(jj diff -r 'reachable(@, mutable())' --name-only |
    while IFS= read -r f; do if [ -f "$f" ]; then printf '%s\\n' "$f"; fi; done)
js_files=$(echo "$files" | grep -E '\\.(js|mjs|cjs|ts|mts|cts|jsx|tsx)$' || true)

echo "$js_files" | xargs -r pnpm exec eslint --fix
"""]
